jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm run e2e
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
